source "https://rubygems.org"

gem "lita"

gem "lita-slack"

gem "lita-meme"
gem "lita-hue", github: 'donaldguy/lita-hue'

gem "plex-ruby"
gem "fuzzy_match"

# Uncomment to use the HipChat adapter
# gem "lita-hipchat"

# Uncomment to use the IRC adapter
# gem "lita-irc"

# Add handlers to give Lita new functionality.
# For example:
# gem "lita-google-images"
# gem "lita-karma"
